#openqcit python 库错误集锦

##python3 各种库安装错误

### appsettings

python3 环境 下安装不了appsettings
错误内容：

指令：

    pip3 install appsettings
    


    Exception:
    Traceback (most recent call last):
      File "/usr/share/python-wheels/urllib3-1.13.1-py2.py3-none-any.whl/urllib3/connection.py", line 137, in _new_conn
        (self.host, self.port), self.timeout, **extra_kw)
      File "/usr/share/python-wheels/urllib3-1.13.1-py2.py3-none-any.whl/urllib3/util/connection.py", line 91, in create_connection
        raise err
      File "/usr/share/python-wheels/urllib3-1.13.1-py2.py3-none-any.whl/urllib3/util/connection.py", line 81, in create_connection
        sock.connect(sa)
    ConnectionRefusedError: [Errno 111] 拒绝连接
    ......

错误解析：
        
    没有权限 加sudo

指令：

    sudo pip3 install appsettings
    
仍然有错误：

     Traceback (most recent call last):
          File "<string>", line 1, in <module>
          File "/tmp/pip-build-tu6tt7k6/pyyaml/setup.py", line 314, in <module>
            python_requires='>=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*',
          File "/usr/lib/python3.5/distutils/core.py", line 108, in setup
            _setup_distribution = dist = klass(attrs)
          File "/tmp/pip-build-tu6tt7k6/pyyaml/setup.py", line 112, in __init__
            _Distribution.__init__(self, attrs)
          File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 272, in __init__
            _Distribution.__init__(self,attrs)
          File "/usr/lib/python3.5/distutils/dist.py", line 281, in __init__
            self.finalize_options()
          File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 327, in finalize_options
            ep.load()(self, ep.name, value)
          File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2229, in load
            return self.resolve()
          File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2239, in resolve
            raise ImportError(str(exc))
        ImportError: module 'setuptools.dist' has no attribute 'check_specifier'
        
        ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-tu6tt7k6/pyyaml/
    You are using pip version 8.1.1, however version 19.1.1 is available.
    You should consider upgrading via the 'pip install --upgrade pip' command.

错误解析：
    
    pip3 需要更新到19.1.1

指令：

    sudo pip3 install --upgrade pip3
    
然后安装appsettings：


指令：

    sudo pip3 install appsettings
    
仍然报错：

    ERROR: Complete output from command python setup.py egg_info:
        ERROR: Traceback (most recent call last):
          File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2237, in resolve
            return functools.reduce(getattr, self.attrs, module)
        AttributeError: module 'setuptools.dist' has no attribute 'check_specifier'
        
        During handling of the above exception, another exception occurred:
        
        Traceback (most recent call last):
          File "<string>", line 1, in <module>
          File "/tmp/pip-install-yzu1086f/pyyaml/setup.py", line 314, in <module>
            python_requires='>=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*',
          File "/usr/lib/python3.5/distutils/core.py", line 108, in setup
            _setup_distribution = dist = klass(attrs)
          File "/tmp/pip-install-yzu1086f/pyyaml/setup.py", line 112, in __init__
            _Distribution.__init__(self, attrs)
          File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 272, in __init__
            _Distribution.__init__(self,attrs)
          File "/usr/lib/python3.5/distutils/dist.py", line 281, in __init__
            self.finalize_options()
          File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 327, in finalize_options
            ep.load()(self, ep.name, value)
          File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2229, in load
            return self.resolve()
          File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2239, in resolve
            raise ImportError(str(exc))
        ImportError: module 'setuptools.dist' has no attribute 'check_specifier'
        ----------------------------------------
    ERROR: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-yzu1086f/pyyaml/

错误分析：

    setuptools 默认版本太低 需强制更新版本
    
指令：
    
    sudo pip3 install setuptools==33.1.1

安装成功后再安装appsettings

指令：
    
    sudo pip3 install appsettings

安装成功，即可正常使用appsettings
